version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Jakarta"
    labels:
      - "dependencies"
      - "go"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/web-admin"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:15"
      timezone: "Asia/Jakarta"
    labels:
      - "dependencies"
      - "web-admin"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
      timezone: "Asia/Jakarta"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
