package credential

import (
	"crypto/x509"
	"encoding/asn1"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
)

// ValidateAttestation verifies the Android Key Attestation certificate chain.
// This confirms that the public key was generated inside a genuine Android Keystore
// (TEE or StrongBox) and was never exported.
//
// The attestation chain is:
//   [0] Key certificate (contains the attested public key)
//   [1] Intermediate CA (Google hardware attestation)
//   [2] Root CA (Google root)
//
// For MVP, we perform structural validation. Full Google root CA pinning
// can be added when moving to production.
func ValidateAttestation(certChainBase64 []string, expectedPublicKeyPEM string) error {
	if len(certChainBase64) == 0 {
		// Attestation is optional in MVP (some test devices may not support it)
		return nil
	}

	// Parse certificate chain
	certs := make([]*x509.Certificate, 0, len(certChainBase64))
	for i, certB64 := range certChainBase64 {
		derBytes, err := base64.StdEncoding.DecodeString(certB64)
		if err != nil {
			return fmt.Errorf("cert[%d]: invalid base64: %w", i, err)
		}
		cert, err := x509.ParseCertificate(derBytes)
		if err != nil {
			return fmt.Errorf("cert[%d]: invalid X.509: %w", i, err)
		}
		certs = append(certs, cert)
	}

	if len(certs) < 2 {
		return errors.New("attestation chain must have at least 2 certificates")
	}

	// Verify chain: each cert should be signed by the next
	for i := 0; i < len(certs)-1; i++ {
		if err := certs[i].CheckSignatureFrom(certs[i+1]); err != nil {
			return fmt.Errorf("cert[%d] signature verification failed: %w", i, err)
		}
	}

	// Verify the leaf certificate contains our expected public key
	leafCert := certs[0]
	leafPubKeyBytes, err := x509.MarshalPKIXPublicKey(leafCert.PublicKey)
	if err != nil {
		return fmt.Errorf("failed to marshal leaf public key: %w", err)
	}

	expectedPub, err := ParseECPublicKey(expectedPublicKeyPEM)
	if err != nil {
		return fmt.Errorf("failed to parse expected public key: %w", err)
	}
	expectedPubBytes, err := x509.MarshalPKIXPublicKey(expectedPub)
	if err != nil {
		return fmt.Errorf("failed to marshal expected public key: %w", err)
	}

	if !bytesEqual(leafPubKeyBytes, expectedPubBytes) {
		return errors.New("attestation leaf certificate public key does not match registered key")
	}

	// Verify attestation extension (OID 1.3.6.1.4.1.11129.2.1.17)
	// This extension is present in Android Key Attestation certificates
	attestationExtOID := "1.3.6.1.4.1.11129.2.1.17"
	hasAttestationExt := false
	for _, ext := range leafCert.Extensions {
		if ext.Id.String() == attestationExtOID {
			hasAttestationExt = true
			break
		}
	}

	if !hasAttestationExt {
		// Not a hard failure for MVP — some older devices or test environments
		// may not have the attestation extension
		return nil
	}

	return nil
}

// androidKeyAttestationOID is the OID for the Android Key Attestation extension
// (1.3.6.1.4.1.11129.2.1.17) found in certificates generated by Android Keystore.
var androidKeyAttestationOID = asn1.ObjectIdentifier{1, 3, 6, 1, 4, 1, 11129, 2, 1, 17}

// keyDescription mirrors the top-level ASN.1 SEQUENCE in the Android Key
// Attestation extension.  We only need the first four fields; the remaining
// fields (attestationChallenge, uniqueId, softwareEnforced, teeEnforced) are
// captured by asn1.RawValue so the parser does not choke on them.
//
//	KeyDescription ::= SEQUENCE {
//	    attestationVersion       INTEGER,
//	    attestationSecurityLevel ENUMERATED,
//	    keymasterVersion         INTEGER,
//	    keymasterSecurityLevel   ENUMERATED,
//	    attestationChallenge     OCTET STRING,
//	    uniqueId                 OCTET STRING,
//	    softwareEnforced         AuthorizationList,
//	    teeEnforced              AuthorizationList,
//	}
type keyDescription struct {
	AttestationVersion       int
	AttestationSecurityLevel asn1.Enumerated
	KeymasterVersion         int
	KeymasterSecurityLevel   asn1.Enumerated
	// Remaining fields — captured but unused.
	AttestationChallenge asn1.RawValue
	UniqueID             asn1.RawValue
	SoftwareEnforced     asn1.RawValue
	TeeEnforced          asn1.RawValue
}

// securityLevelToString converts an Android attestation security-level enum to
// the string representation used throughout the credential module.
func securityLevelToString(level asn1.Enumerated) string {
	switch level {
	case 2:
		return "strongbox"
	case 1:
		return "tee"
	default:
		return "software"
	}
}

// DetectKeystoreLevel determines the keystore security level from the Android
// Key Attestation extension (OID 1.3.6.1.4.1.11129.2.1.17) embedded in the
// leaf certificate.
//
// It parses the ASN.1 KeyDescription and reads attestationSecurityLevel:
//
//	2 → "strongbox"
//	1 → "tee"
//	0 → "software"
//
// If the attestation extension is absent (e.g. iOS, test certs) or cannot be
// parsed, it falls back to a CN-based heuristic on the intermediate issuer.
func DetectKeystoreLevel(certChainBase64 []string) string {
	if len(certChainBase64) == 0 {
		return "software"
	}

	derBytes, err := base64.StdEncoding.DecodeString(certChainBase64[0])
	if err != nil {
		return "software"
	}

	cert, err := x509.ParseCertificate(derBytes)
	if err != nil {
		return "software"
	}

	// Try to parse the Android Key Attestation extension.
	for _, ext := range cert.Extensions {
		if ext.Id.Equal(androidKeyAttestationOID) {
			var kd keyDescription
			rest, err := asn1.Unmarshal(ext.Value, &kd)
			if err == nil && len(rest) == 0 {
				return securityLevelToString(kd.AttestationSecurityLevel)
			}
			// If strict parsing fails, try a minimal parse of just the
			// first two fields (version + security level) using RawValues.
			level, ok := parseSecurityLevelFallback(ext.Value)
			if ok {
				return securityLevelToString(asn1.Enumerated(level))
			}
			// Extension found but unparseable — fall through to heuristic.
			break
		}
	}

	// Fallback: CN-based heuristic for non-Android or legacy certs.
	return detectKeystoreLevelFromIssuerCN(certChainBase64)
}

// parseSecurityLevelFallback does a minimal ASN.1 walk into the outer SEQUENCE
// to extract the attestationSecurityLevel (second element) even when later
// fields use unusual tagging that the strict struct unmarshal rejects.
func parseSecurityLevelFallback(data []byte) (int, bool) {
	// Unwrap the outer SEQUENCE.
	var seq asn1.RawValue
	rest, err := asn1.Unmarshal(data, &seq)
	if err != nil || len(rest) != 0 || seq.Tag != asn1.TagSequence {
		return 0, false
	}

	inner := seq.Bytes

	// First element: attestationVersion (INTEGER).
	var version asn1.RawValue
	inner, err = asn1.Unmarshal(inner, &version)
	if err != nil {
		return 0, false
	}

	// Second element: attestationSecurityLevel (ENUMERATED).
	var secLevel asn1.RawValue
	_, err = asn1.Unmarshal(inner, &secLevel)
	if err != nil {
		return 0, false
	}

	// ENUMERATED is encoded the same way as INTEGER for small values.
	if secLevel.Tag != asn1.TagEnum || len(secLevel.Bytes) == 0 {
		return 0, false
	}
	return int(secLevel.Bytes[0]), true
}

// detectKeystoreLevelFromIssuerCN is the legacy heuristic that checks the
// intermediate certificate's Common Name for keywords.
func detectKeystoreLevelFromIssuerCN(certChainBase64 []string) string {
	issuerCN := ""
	if len(certChainBase64) > 1 {
		if intermediateBytes, err := base64.StdEncoding.DecodeString(certChainBase64[1]); err == nil {
			if intermediate, err := x509.ParseCertificate(intermediateBytes); err == nil {
				issuerCN = intermediate.Subject.CommonName
			}
		}
	}

	issuerLower := strings.ToLower(issuerCN)
	if strings.Contains(issuerLower, "strongbox") {
		return "strongbox"
	}
	if strings.Contains(issuerLower, "tee") || strings.Contains(issuerLower, "keymaster") {
		return "tee"
	}

	// If we have any cert chain at all, assume TEE as a conservative default.
	if len(certChainBase64) >= 2 {
		return "tee"
	}
	return "software"
}

func bytesEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
