// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const deleteAuthRefreshSession = `-- name: DeleteAuthRefreshSession :exec
delete from mistypass_auth_refresh_sessions where session_id = $1
`

func (q *Queries) DeleteAuthRefreshSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthRefreshSession, sessionID)
	return err
}

const deleteAuthRefreshSessionsByUserID = `-- name: DeleteAuthRefreshSessionsByUserID :execrows
delete from mistypass_auth_refresh_sessions where user_id = $1
`

func (q *Queries) DeleteAuthRefreshSessionsByUserID(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuthRefreshSessionsByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredAuthRevokedAccessToken = `-- name: DeleteExpiredAuthRevokedAccessToken :exec
delete from mistypass_auth_revoked_access_tokens
where token_id = $1 and expires_at <= $2
`

type DeleteExpiredAuthRevokedAccessTokenParams struct {
	TokenID   string
	ExpiresAt time.Time
}

func (q *Queries) DeleteExpiredAuthRevokedAccessToken(ctx context.Context, arg DeleteExpiredAuthRevokedAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthRevokedAccessToken, arg.TokenID, arg.ExpiresAt)
	return err
}

const getAuthRefreshSession = `-- name: GetAuthRefreshSession :one
select user_id, expires_at
from mistypass_auth_refresh_sessions
where session_id = $1
`

type GetAuthRefreshSessionRow struct {
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) GetAuthRefreshSession(ctx context.Context, sessionID string) (GetAuthRefreshSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthRefreshSession, sessionID)
	var i GetAuthRefreshSessionRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const getAuthRevokedAccessTokenExpiresAt = `-- name: GetAuthRevokedAccessTokenExpiresAt :one
select expires_at
from mistypass_auth_revoked_access_tokens
where token_id = $1
`

func (q *Queries) GetAuthRevokedAccessTokenExpiresAt(ctx context.Context, tokenID string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getAuthRevokedAccessTokenExpiresAt, tokenID)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
select id, email, role, tenant_id, building_ids, password_hash
from mistypass_auth_users
where lower(email) = $1
`

type GetAuthUserByEmailRow struct {
	ID           string
	Email        string
	Role         string
	TenantID     string
	BuildingIds  json.RawMessage
	PasswordHash []byte
}

func (q *Queries) GetAuthUserByEmail(ctx context.Context, email string) (GetAuthUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthUserByEmail, email)
	var i GetAuthUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.TenantID,
		&i.BuildingIds,
		&i.PasswordHash,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
select id, email, role, tenant_id, building_ids, password_hash
from mistypass_auth_users
where id = $1
`

type GetAuthUserByIDRow struct {
	ID           string
	Email        string
	Role         string
	TenantID     string
	BuildingIds  json.RawMessage
	PasswordHash []byte
}

func (q *Queries) GetAuthUserByID(ctx context.Context, id string) (GetAuthUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthUserByID, id)
	var i GetAuthUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.TenantID,
		&i.BuildingIds,
		&i.PasswordHash,
	)
	return i, err
}

const getGatewayDeviceTokenHash = `-- name: GetGatewayDeviceTokenHash :one
select token_hash
from mistypass_gateway_device_tokens
where gateway_id = $1
`

func (q *Queries) GetGatewayDeviceTokenHash(ctx context.Context, gatewayID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGatewayDeviceTokenHash, gatewayID)
	var token_hash string
	err := row.Scan(&token_hash)
	return token_hash, err
}

const upsertAuthRefreshSession = `-- name: UpsertAuthRefreshSession :exec
insert into mistypass_auth_refresh_sessions (session_id, user_id, expires_at, created_at, updated_at)
values ($1, $2, $3, now(), now())
on conflict (session_id) do update
set user_id = excluded.user_id,
    expires_at = excluded.expires_at,
    updated_at = now()
`

type UpsertAuthRefreshSessionParams struct {
	SessionID string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) UpsertAuthRefreshSession(ctx context.Context, arg UpsertAuthRefreshSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertAuthRefreshSession, arg.SessionID, arg.UserID, arg.ExpiresAt)
	return err
}

const upsertAuthRevokedAccessToken = `-- name: UpsertAuthRevokedAccessToken :exec
insert into mistypass_auth_revoked_access_tokens (token_id, expires_at, created_at, updated_at)
values ($1, $2, now(), now())
on conflict (token_id) do update
set expires_at = excluded.expires_at,
    updated_at = now()
`

type UpsertAuthRevokedAccessTokenParams struct {
	TokenID   string
	ExpiresAt time.Time
}

func (q *Queries) UpsertAuthRevokedAccessToken(ctx context.Context, arg UpsertAuthRevokedAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertAuthRevokedAccessToken, arg.TokenID, arg.ExpiresAt)
	return err
}

const upsertAuthUser = `-- name: UpsertAuthUser :exec
insert into mistypass_auth_users (id, email, role, tenant_id, building_ids, password_hash, created_at, updated_at)
values ($1, $2, $3, $4, $5, $6, now(), now())
on conflict (id) do update
set email = excluded.email,
    role = excluded.role,
    tenant_id = excluded.tenant_id,
    building_ids = excluded.building_ids,
    password_hash = excluded.password_hash,
    updated_at = now()
`

type UpsertAuthUserParams struct {
	ID           string
	Email        string
	Role         string
	TenantID     string
	BuildingIds  json.RawMessage
	PasswordHash []byte
}

func (q *Queries) UpsertAuthUser(ctx context.Context, arg UpsertAuthUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertAuthUser,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.TenantID,
		arg.BuildingIds,
		arg.PasswordHash,
	)
	return err
}

const upsertGatewayDeviceToken = `-- name: UpsertGatewayDeviceToken :exec
insert into mistypass_gateway_device_tokens (gateway_id, token_hash, created_at, updated_at)
values ($1, $2, now(), now())
on conflict (gateway_id) do update
set token_hash = excluded.token_hash,
    updated_at = now()
`

type UpsertGatewayDeviceTokenParams struct {
	GatewayID string
	TokenHash string
}

func (q *Queries) UpsertGatewayDeviceToken(ctx context.Context, arg UpsertGatewayDeviceTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertGatewayDeviceToken, arg.GatewayID, arg.TokenHash)
	return err
}
