// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Mistypass struct {
	StateKey  string
	Payload   json.RawMessage
	UpdatedAt time.Time
}

type MistypassAccessEvent struct {
	ID         string
	TenantID   string
	BuildingID sql.NullString
	AreaID     sql.NullString
	EventType  sql.NullString
	Actor      sql.NullString
	DoorID     sql.NullString
	GatewayID  sql.NullString
	Result     sql.NullString
	At         time.Time
	Raw        json.RawMessage
	SyncedAt   time.Time
}

type MistypassAccessPolicy struct {
	ID         string
	TenantID   string
	Name       string
	ScopeType  string
	BuildingID sql.NullString
	AreaID     sql.NullString
	DoorID     sql.NullString
	Schedule   sql.NullString
	Members    int32
	Status     string
	UpdatedAt  time.Time
	Raw        json.RawMessage
	SyncedAt   time.Time
}

type MistypassAccessUser struct {
	ID         string
	TenantID   string
	BuildingID sql.NullString
	Name       string
	Email      string
	Role       string
	Status     string
	GroupIds   pqtype.NullRawMessage
	CreatedAt  time.Time
	Raw        json.RawMessage
	SyncedAt   time.Time
}

type MistypassAccessUserGroup struct {
	ID          string
	TenantID    string
	BuildingID  sql.NullString
	Name        string
	Description sql.NullString
	Members     pqtype.NullRawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Raw         json.RawMessage
	SyncedAt    time.Time
}

type MistypassAlarm struct {
	ID         string
	TenantID   string
	BuildingID sql.NullString
	AreaID     sql.NullString
	DoorID     sql.NullString
	AlarmType  sql.NullString
	Severity   sql.NullString
	Location   sql.NullString
	Status     sql.NullString
	CreatedAt  time.Time
	Raw        json.RawMessage
	SyncedAt   time.Time
}

type MistypassArea struct {
	ID         string
	TenantID   string
	BuildingID string
	FloorID    string
	Name       string
	CreatedAt  time.Time
	Raw        json.RawMessage
	SyncedAt   time.Time
}

type MistypassAuditLog struct {
	ID       string
	TenantID string
	Actor    sql.NullString
	Role     sql.NullString
	Action   sql.NullString
	Target   sql.NullString
	Source   sql.NullString
	At       time.Time
	Raw      json.RawMessage
	SyncedAt time.Time
}

type MistypassAuthRefreshSession struct {
	SessionID string
	UserID    string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MistypassAuthRevokedAccessToken struct {
	TokenID   string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MistypassAuthUser struct {
	ID           string
	Name         string
	Email        string
	Role         string
	TenantID     string
	BuildingIds  json.RawMessage
	Language     string
	PasswordHash []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MistypassBuilding struct {
	ID        string
	TenantID  string
	Name      string
	Address   sql.NullString
	Region    sql.NullString
	CreatedAt time.Time
	Raw       json.RawMessage
	SyncedAt  time.Time
}

type MistypassChangeLog struct {
	ID          int64
	StateKey    string
	ChangeType  string
	PayloadHash string
	Payload     json.RawMessage
	CreatedAt   time.Time
}

type MistypassChangeReplayCheckpoint struct {
	StateKey     string
	LastChangeID int64
	UpdatedAt    time.Time
}

type MistypassDeviceEvent struct {
	ID         string
	TenantID   string
	BuildingID sql.NullString
	EventType  sql.NullString
	GatewayID  sql.NullString
	Detail     sql.NullString
	Result     sql.NullString
	At         time.Time
	Raw        json.RawMessage
	SyncedAt   time.Time
}

type MistypassDoor struct {
	ID         string
	TenantID   string
	BuildingID string
	FloorID    string
	AreaID     string
	Name       string
	GatewayID  sql.NullString
	Kind       string
	Status     string
	CreatedAt  time.Time
	Raw        json.RawMessage
	SyncedAt   time.Time
}

type MistypassDoorGroup struct {
	ID        string
	TenantID  string
	Name      string
	DoorIds   pqtype.NullRawMessage
	CreatedAt time.Time
	Raw       json.RawMessage
	SyncedAt  time.Time
}

type MistypassEnterpriseDomainMapping struct {
	ID        string
	TenantID  string
	Domain    string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	Raw       json.RawMessage
	SyncedAt  time.Time
}

type MistypassEnterpriseEmployee struct {
	ID           string
	TenantID     string
	ExternalID   sql.NullString
	Email        string
	FullName     string
	Department   sql.NullString
	JobTitle     sql.NullString
	Location     sql.NullString
	AccessRole   sql.NullString
	BuildingID   sql.NullString
	GroupIds     pqtype.NullRawMessage
	Status       sql.NullString
	Source       sql.NullString
	LastSyncedAt time.Time
	Raw          json.RawMessage
	SyncedAt     time.Time
}

type MistypassEnterpriseIdpConfig struct {
	ID        string
	TenantID  string
	Provider  string
	IssuerUrl string
	ClientID  string
	Status    string
	SyncMode  string
	Scopes    pqtype.NullRawMessage
	UpdatedBy sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	Raw       json.RawMessage
	SyncedAt  time.Time
}

type MistypassEnterpriseSyncJob struct {
	ID          string
	TenantID    string
	Source      sql.NullString
	Status      sql.NullString
	Total       sql.NullInt32
	Created     sql.NullInt32
	Updated     sql.NullInt32
	Deactivated sql.NullInt32
	Rejected    sql.NullInt32
	Actor       sql.NullString
	StartedAt   time.Time
	EndedAt     time.Time
	Raw         json.RawMessage
	SyncedAt    time.Time
}

type MistypassFloor struct {
	ID         string
	TenantID   string
	BuildingID string
	Name       string
	CreatedAt  time.Time
	Raw        json.RawMessage
	SyncedAt   time.Time
}

type MistypassGateway struct {
	ID             string
	TenantID       string
	SerialNumber   string
	BuildingID     sql.NullString
	DeviceCapacity int32
	Status         string
	LastSeenAt     time.Time
	Devices        pqtype.NullRawMessage
	BoundDoorIds   pqtype.NullRawMessage
	Raw            json.RawMessage
	SyncedAt       time.Time
}

type MistypassGatewayDevice struct {
	ID           string
	GatewayID    string
	TenantID     string
	SerialNumber string
	Kind         string
	Source       string
	Protocol     sql.NullString
	Rs485Config  pqtype.NullRawMessage
	Rs485Health  pqtype.NullRawMessage
	Status       string
	LastSeenAt   time.Time
	Raw          json.RawMessage
	SyncedAt     time.Time
}

type MistypassGatewayDeviceToken struct {
	GatewayID string
	TokenHash string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MistypassGatewaySerialInventory struct {
	ID                string
	TenantID          string
	SerialNumber      string
	ProductType       string
	Status            string
	BatchCode         sql.NullString
	Source            sql.NullString
	ConsumedGatewayID sql.NullString
	ConsumedAt        sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Raw               json.RawMessage
	SyncedAt          time.Time
}

type MistypassTemporaryAccess struct {
	ID                string
	TenantID          string
	ScopeType         string
	BuildingID        sql.NullString
	AreaID            sql.NullString
	DoorID            sql.NullString
	DeliveryMethod    string
	GranteeName       string
	GranteeEmail      string
	GranteePhone      string
	ValidUntil        string
	AuthorizedByEmail sql.NullString
	AuthorizedByRole  sql.NullString
	AuthorizedAt      time.Time
	CreatedAt         time.Time
	Raw               json.RawMessage
	SyncedAt          time.Time
}

type MistypassTenant struct {
	ID         string
	Name       string
	TenantType string
	HqRegion   string
	Status     string
	CreatedAt  time.Time
	Raw        json.RawMessage
	SyncedAt   time.Time
}

type MistypassVisitorPass struct {
	ID             string
	TenantID       string
	BuildingID     sql.NullString
	Host           string
	Visitor        string
	DeliveryMethod string
	ExpiresAt      string
	CreatedAt      time.Time
	Raw            json.RawMessage
	SyncedAt       time.Time
}

type MistypassWalletAuditLog struct {
	ID       string
	TenantID string
	Action   sql.NullString
	Actor    sql.NullString
	TargetID sql.NullString
	Result   sql.NullString
	At       time.Time
	Raw      json.RawMessage
	SyncedAt time.Time
}

type MistypassWalletConfig struct {
	ID                  string
	TenantID            string
	Provider            string
	IssuerID            string
	ServiceAccountEmail string
	KeyRef              string
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Raw                 json.RawMessage
	SyncedAt            time.Time
}

type MistypassWalletJob struct {
	ID           string
	TenantID     string
	Provider     sql.NullString
	BatchID      sql.NullString
	TemplateID   sql.NullString
	TargetType   sql.NullString
	TargetID     sql.NullString
	ExpiresAt    sql.NullString
	PassID       sql.NullString
	Status       sql.NullString
	RetryCount   sql.NullInt32
	ErrorCode    sql.NullString
	ErrorMessage sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Raw          json.RawMessage
	SyncedAt     time.Time
}

type MistypassWalletPass struct {
	ID          string
	TenantID    string
	Provider    string
	TemplateID  string
	TargetType  string
	TargetID    string
	ObjectID    string
	Status      string
	SaveLink    string
	ExpiresAt   sql.NullString
	IssuedAt    time.Time
	ActivatedAt sql.NullTime
	RevokedAt   sql.NullTime
	CreatedBy   sql.NullString
	UpdatedBy   sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Raw         json.RawMessage
	SyncedAt    time.Time
}

type MistypassWalletTemplate struct {
	ID          string
	TenantID    string
	Provider    string
	PassType    string
	ClassID     string
	Name        string
	Status      string
	StyleConfig pqtype.NullRawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Raw         json.RawMessage
	SyncedAt    time.Time
}
