// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projection_wallet.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const upsertProjectionWalletAuditLog = `-- name: UpsertProjectionWalletAuditLog :exec
insert into mistypass_wallet_audit_logs (id, tenant_id, action, actor, target_id, result, at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    action = excluded.action,
    actor = excluded.actor,
    target_id = excluded.target_id,
    result = excluded.result,
    at = excluded.at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionWalletAuditLogParams struct {
	ID       string
	TenantID string
	Action   sql.NullString
	Actor    sql.NullString
	TargetID sql.NullString
	Result   sql.NullString
	At       time.Time
	Raw      json.RawMessage
}

func (q *Queries) UpsertProjectionWalletAuditLog(ctx context.Context, arg UpsertProjectionWalletAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionWalletAuditLog,
		arg.ID,
		arg.TenantID,
		arg.Action,
		arg.Actor,
		arg.TargetID,
		arg.Result,
		arg.At,
		arg.Raw,
	)
	return err
}

const upsertProjectionWalletConfig = `-- name: UpsertProjectionWalletConfig :exec
insert into mistypass_wallet_configs (id, tenant_id, provider, issuer_id, service_account_email, key_ref, status, created_at, updated_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    provider = excluded.provider,
    issuer_id = excluded.issuer_id,
    service_account_email = excluded.service_account_email,
    key_ref = excluded.key_ref,
    status = excluded.status,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionWalletConfigParams struct {
	ID                  string
	TenantID            string
	Provider            string
	IssuerID            string
	ServiceAccountEmail string
	KeyRef              string
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Raw                 json.RawMessage
}

func (q *Queries) UpsertProjectionWalletConfig(ctx context.Context, arg UpsertProjectionWalletConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionWalletConfig,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.IssuerID,
		arg.ServiceAccountEmail,
		arg.KeyRef,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionWalletJob = `-- name: UpsertProjectionWalletJob :exec
insert into mistypass_wallet_jobs (id, tenant_id, provider, batch_id, template_id, target_type, target_id, expires_at, pass_id, status, retry_count, error_code, error_message, created_at, updated_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    provider = excluded.provider,
    batch_id = excluded.batch_id,
    template_id = excluded.template_id,
    target_type = excluded.target_type,
    target_id = excluded.target_id,
    expires_at = excluded.expires_at,
    pass_id = excluded.pass_id,
    status = excluded.status,
    retry_count = excluded.retry_count,
    error_code = excluded.error_code,
    error_message = excluded.error_message,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionWalletJobParams struct {
	ID           string
	TenantID     string
	Provider     sql.NullString
	BatchID      sql.NullString
	TemplateID   sql.NullString
	TargetType   sql.NullString
	TargetID     sql.NullString
	ExpiresAt    sql.NullString
	PassID       sql.NullString
	Status       sql.NullString
	RetryCount   sql.NullInt32
	ErrorCode    sql.NullString
	ErrorMessage sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Raw          json.RawMessage
}

func (q *Queries) UpsertProjectionWalletJob(ctx context.Context, arg UpsertProjectionWalletJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionWalletJob,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.BatchID,
		arg.TemplateID,
		arg.TargetType,
		arg.TargetID,
		arg.ExpiresAt,
		arg.PassID,
		arg.Status,
		arg.RetryCount,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionWalletPass = `-- name: UpsertProjectionWalletPass :exec
insert into mistypass_wallet_passes (id, tenant_id, provider, template_id, target_type, target_id, object_id, status, save_link, expires_at, issued_at, activated_at, revoked_at, created_by, updated_by, created_at, updated_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    provider = excluded.provider,
    template_id = excluded.template_id,
    target_type = excluded.target_type,
    target_id = excluded.target_id,
    object_id = excluded.object_id,
    status = excluded.status,
    save_link = excluded.save_link,
    expires_at = excluded.expires_at,
    issued_at = excluded.issued_at,
    activated_at = excluded.activated_at,
    revoked_at = excluded.revoked_at,
    created_by = excluded.created_by,
    updated_by = excluded.updated_by,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionWalletPassParams struct {
	ID          string
	TenantID    string
	Provider    string
	TemplateID  string
	TargetType  string
	TargetID    string
	ObjectID    string
	Status      string
	SaveLink    string
	ExpiresAt   sql.NullString
	IssuedAt    time.Time
	ActivatedAt sql.NullTime
	RevokedAt   sql.NullTime
	CreatedBy   sql.NullString
	UpdatedBy   sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Raw         json.RawMessage
}

func (q *Queries) UpsertProjectionWalletPass(ctx context.Context, arg UpsertProjectionWalletPassParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionWalletPass,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.TemplateID,
		arg.TargetType,
		arg.TargetID,
		arg.ObjectID,
		arg.Status,
		arg.SaveLink,
		arg.ExpiresAt,
		arg.IssuedAt,
		arg.ActivatedAt,
		arg.RevokedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionWalletTemplate = `-- name: UpsertProjectionWalletTemplate :exec
insert into mistypass_wallet_templates (id, tenant_id, provider, pass_type, class_id, name, status, style_config, created_at, updated_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    provider = excluded.provider,
    pass_type = excluded.pass_type,
    class_id = excluded.class_id,
    name = excluded.name,
    status = excluded.status,
    style_config = excluded.style_config,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionWalletTemplateParams struct {
	ID          string
	TenantID    string
	Provider    string
	PassType    string
	ClassID     string
	Name        string
	Status      string
	StyleConfig pqtype.NullRawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Raw         json.RawMessage
}

func (q *Queries) UpsertProjectionWalletTemplate(ctx context.Context, arg UpsertProjectionWalletTemplateParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionWalletTemplate,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.PassType,
		arg.ClassID,
		arg.Name,
		arg.Status,
		arg.StyleConfig,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Raw,
	)
	return err
}
