// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projection_enterprise.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const upsertProjectionEnterpriseDomainMapping = `-- name: UpsertProjectionEnterpriseDomainMapping :exec
insert into mistypass_enterprise_domain_mappings (id, tenant_id, domain, status, created_at, updated_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    domain = excluded.domain,
    status = excluded.status,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionEnterpriseDomainMappingParams struct {
	ID        string
	TenantID  string
	Domain    string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	Raw       json.RawMessage
}

func (q *Queries) UpsertProjectionEnterpriseDomainMapping(ctx context.Context, arg UpsertProjectionEnterpriseDomainMappingParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionEnterpriseDomainMapping,
		arg.ID,
		arg.TenantID,
		arg.Domain,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionEnterpriseEmployee = `-- name: UpsertProjectionEnterpriseEmployee :exec
insert into mistypass_enterprise_employees (id, tenant_id, external_id, email, full_name, department, job_title, location, access_role, building_id, group_ids, status, source, last_synced_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    external_id = excluded.external_id,
    email = excluded.email,
    full_name = excluded.full_name,
    department = excluded.department,
    job_title = excluded.job_title,
    location = excluded.location,
    access_role = excluded.access_role,
    building_id = excluded.building_id,
    group_ids = excluded.group_ids,
    status = excluded.status,
    source = excluded.source,
    last_synced_at = excluded.last_synced_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionEnterpriseEmployeeParams struct {
	ID           string
	TenantID     string
	ExternalID   sql.NullString
	Email        string
	FullName     string
	Department   sql.NullString
	JobTitle     sql.NullString
	Location     sql.NullString
	AccessRole   sql.NullString
	BuildingID   sql.NullString
	GroupIds     pqtype.NullRawMessage
	Status       sql.NullString
	Source       sql.NullString
	LastSyncedAt time.Time
	Raw          json.RawMessage
}

func (q *Queries) UpsertProjectionEnterpriseEmployee(ctx context.Context, arg UpsertProjectionEnterpriseEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionEnterpriseEmployee,
		arg.ID,
		arg.TenantID,
		arg.ExternalID,
		arg.Email,
		arg.FullName,
		arg.Department,
		arg.JobTitle,
		arg.Location,
		arg.AccessRole,
		arg.BuildingID,
		arg.GroupIds,
		arg.Status,
		arg.Source,
		arg.LastSyncedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionEnterpriseIDPConfig = `-- name: UpsertProjectionEnterpriseIDPConfig :exec
insert into mistypass_enterprise_idp_configs (id, tenant_id, provider, issuer_url, client_id, status, sync_mode, scopes, updated_by, created_at, updated_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    provider = excluded.provider,
    issuer_url = excluded.issuer_url,
    client_id = excluded.client_id,
    status = excluded.status,
    sync_mode = excluded.sync_mode,
    scopes = excluded.scopes,
    updated_by = excluded.updated_by,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionEnterpriseIDPConfigParams struct {
	ID        string
	TenantID  string
	Provider  string
	IssuerUrl string
	ClientID  string
	Status    string
	SyncMode  string
	Scopes    pqtype.NullRawMessage
	UpdatedBy sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	Raw       json.RawMessage
}

func (q *Queries) UpsertProjectionEnterpriseIDPConfig(ctx context.Context, arg UpsertProjectionEnterpriseIDPConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionEnterpriseIDPConfig,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.IssuerUrl,
		arg.ClientID,
		arg.Status,
		arg.SyncMode,
		arg.Scopes,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionEnterpriseSyncJob = `-- name: UpsertProjectionEnterpriseSyncJob :exec
insert into mistypass_enterprise_sync_jobs (id, tenant_id, source, status, total, created, updated, deactivated, rejected, actor, started_at, ended_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    source = excluded.source,
    status = excluded.status,
    total = excluded.total,
    created = excluded.created,
    updated = excluded.updated,
    deactivated = excluded.deactivated,
    rejected = excluded.rejected,
    actor = excluded.actor,
    started_at = excluded.started_at,
    ended_at = excluded.ended_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionEnterpriseSyncJobParams struct {
	ID          string
	TenantID    string
	Source      sql.NullString
	Status      sql.NullString
	Total       sql.NullInt32
	Created     sql.NullInt32
	Updated     sql.NullInt32
	Deactivated sql.NullInt32
	Rejected    sql.NullInt32
	Actor       sql.NullString
	StartedAt   time.Time
	EndedAt     time.Time
	Raw         json.RawMessage
}

func (q *Queries) UpsertProjectionEnterpriseSyncJob(ctx context.Context, arg UpsertProjectionEnterpriseSyncJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionEnterpriseSyncJob,
		arg.ID,
		arg.TenantID,
		arg.Source,
		arg.Status,
		arg.Total,
		arg.Created,
		arg.Updated,
		arg.Deactivated,
		arg.Rejected,
		arg.Actor,
		arg.StartedAt,
		arg.EndedAt,
		arg.Raw,
	)
	return err
}
