// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projection_gateway.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const upsertProjectionGateway = `-- name: UpsertProjectionGateway :exec
insert into mistypass_gateways (id, tenant_id, serial_number, building_id, device_capacity, status, last_seen_at, devices, bound_door_ids, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    serial_number = excluded.serial_number,
    building_id = excluded.building_id,
    device_capacity = excluded.device_capacity,
    status = excluded.status,
    last_seen_at = excluded.last_seen_at,
    devices = excluded.devices,
    bound_door_ids = excluded.bound_door_ids,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionGatewayParams struct {
	ID             string
	TenantID       string
	SerialNumber   string
	BuildingID     sql.NullString
	DeviceCapacity int32
	Status         string
	LastSeenAt     time.Time
	Devices        pqtype.NullRawMessage
	BoundDoorIds   pqtype.NullRawMessage
	Raw            json.RawMessage
}

func (q *Queries) UpsertProjectionGateway(ctx context.Context, arg UpsertProjectionGatewayParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionGateway,
		arg.ID,
		arg.TenantID,
		arg.SerialNumber,
		arg.BuildingID,
		arg.DeviceCapacity,
		arg.Status,
		arg.LastSeenAt,
		arg.Devices,
		arg.BoundDoorIds,
		arg.Raw,
	)
	return err
}

const upsertProjectionGatewayDevice = `-- name: UpsertProjectionGatewayDevice :exec
insert into mistypass_gateway_devices (id, gateway_id, tenant_id, serial_number, kind, source, protocol, rs485_config, rs485_health, status, last_seen_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
on conflict (id) do update
set gateway_id = excluded.gateway_id,
    tenant_id = excluded.tenant_id,
    serial_number = excluded.serial_number,
    kind = excluded.kind,
    source = excluded.source,
    protocol = excluded.protocol,
    rs485_config = excluded.rs485_config,
    rs485_health = excluded.rs485_health,
    status = excluded.status,
    last_seen_at = excluded.last_seen_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionGatewayDeviceParams struct {
	ID           string
	GatewayID    string
	TenantID     string
	SerialNumber string
	Kind         string
	Source       string
	Protocol     sql.NullString
	Rs485Config  pqtype.NullRawMessage
	Rs485Health  pqtype.NullRawMessage
	Status       string
	LastSeenAt   time.Time
	Raw          json.RawMessage
}

func (q *Queries) UpsertProjectionGatewayDevice(ctx context.Context, arg UpsertProjectionGatewayDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionGatewayDevice,
		arg.ID,
		arg.GatewayID,
		arg.TenantID,
		arg.SerialNumber,
		arg.Kind,
		arg.Source,
		arg.Protocol,
		arg.Rs485Config,
		arg.Rs485Health,
		arg.Status,
		arg.LastSeenAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionGatewaySerialInventory = `-- name: UpsertProjectionGatewaySerialInventory :exec
insert into mistypass_gateway_serial_inventory (
  id, tenant_id, serial_number, product_type, status, batch_code, source, consumed_gateway_id, consumed_at, created_at, updated_at, raw, synced_at
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    serial_number = excluded.serial_number,
    product_type = excluded.product_type,
    status = excluded.status,
    batch_code = excluded.batch_code,
    source = excluded.source,
    consumed_gateway_id = excluded.consumed_gateway_id,
    consumed_at = excluded.consumed_at,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionGatewaySerialInventoryParams struct {
	ID                string
	TenantID          string
	SerialNumber      string
	ProductType       string
	Status            string
	BatchCode         sql.NullString
	Source            sql.NullString
	ConsumedGatewayID sql.NullString
	ConsumedAt        sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Raw               json.RawMessage
}

func (q *Queries) UpsertProjectionGatewaySerialInventory(ctx context.Context, arg UpsertProjectionGatewaySerialInventoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionGatewaySerialInventory,
		arg.ID,
		arg.TenantID,
		arg.SerialNumber,
		arg.ProductType,
		arg.Status,
		arg.BatchCode,
		arg.Source,
		arg.ConsumedGatewayID,
		arg.ConsumedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Raw,
	)
	return err
}
