// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projection_space.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const upsertProjectionArea = `-- name: UpsertProjectionArea :exec
insert into mistypass_areas (id, tenant_id, building_id, floor_id, name, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    building_id = excluded.building_id,
    floor_id = excluded.floor_id,
    name = excluded.name,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionAreaParams struct {
	ID         string
	TenantID   string
	BuildingID string
	FloorID    string
	Name       string
	CreatedAt  time.Time
	Raw        json.RawMessage
}

func (q *Queries) UpsertProjectionArea(ctx context.Context, arg UpsertProjectionAreaParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionArea,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.FloorID,
		arg.Name,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionBuilding = `-- name: UpsertProjectionBuilding :exec
insert into mistypass_buildings (id, tenant_id, name, address, region, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    name = excluded.name,
    address = excluded.address,
    region = excluded.region,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionBuildingParams struct {
	ID        string
	TenantID  string
	Name      string
	Address   sql.NullString
	Region    sql.NullString
	CreatedAt time.Time
	Raw       json.RawMessage
}

func (q *Queries) UpsertProjectionBuilding(ctx context.Context, arg UpsertProjectionBuildingParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionBuilding,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.Region,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionDoor = `-- name: UpsertProjectionDoor :exec
insert into mistypass_doors (id, tenant_id, building_id, floor_id, area_id, name, gateway_id, kind, status, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    building_id = excluded.building_id,
    floor_id = excluded.floor_id,
    area_id = excluded.area_id,
    name = excluded.name,
    gateway_id = excluded.gateway_id,
    kind = excluded.kind,
    status = excluded.status,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionDoorParams struct {
	ID         string
	TenantID   string
	BuildingID string
	FloorID    string
	AreaID     string
	Name       string
	GatewayID  sql.NullString
	Kind       string
	Status     string
	CreatedAt  time.Time
	Raw        json.RawMessage
}

func (q *Queries) UpsertProjectionDoor(ctx context.Context, arg UpsertProjectionDoorParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionDoor,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.FloorID,
		arg.AreaID,
		arg.Name,
		arg.GatewayID,
		arg.Kind,
		arg.Status,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionDoorGroup = `-- name: UpsertProjectionDoorGroup :exec
insert into mistypass_door_groups (id, tenant_id, name, door_ids, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    name = excluded.name,
    door_ids = excluded.door_ids,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionDoorGroupParams struct {
	ID        string
	TenantID  string
	Name      string
	DoorIds   pqtype.NullRawMessage
	CreatedAt time.Time
	Raw       json.RawMessage
}

func (q *Queries) UpsertProjectionDoorGroup(ctx context.Context, arg UpsertProjectionDoorGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionDoorGroup,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.DoorIds,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionFloor = `-- name: UpsertProjectionFloor :exec
insert into mistypass_floors (id, tenant_id, building_id, name, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    building_id = excluded.building_id,
    name = excluded.name,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionFloorParams struct {
	ID         string
	TenantID   string
	BuildingID string
	Name       string
	CreatedAt  time.Time
	Raw        json.RawMessage
}

func (q *Queries) UpsertProjectionFloor(ctx context.Context, arg UpsertProjectionFloorParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionFloor,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.Name,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}
