// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projection_access.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const upsertProjectionAccessPolicy = `-- name: UpsertProjectionAccessPolicy :exec
insert into mistypass_access_policies (id, tenant_id, name, scope_type, building_id, area_id, door_id, schedule, members, status, updated_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    name = excluded.name,
    scope_type = excluded.scope_type,
    building_id = excluded.building_id,
    area_id = excluded.area_id,
    door_id = excluded.door_id,
    schedule = excluded.schedule,
    members = excluded.members,
    status = excluded.status,
    updated_at = excluded.updated_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionAccessPolicyParams struct {
	ID         string
	TenantID   string
	Name       string
	ScopeType  string
	BuildingID sql.NullString
	AreaID     sql.NullString
	DoorID     sql.NullString
	Schedule   sql.NullString
	Members    int32
	Status     string
	UpdatedAt  time.Time
	Raw        json.RawMessage
}

func (q *Queries) UpsertProjectionAccessPolicy(ctx context.Context, arg UpsertProjectionAccessPolicyParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionAccessPolicy,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ScopeType,
		arg.BuildingID,
		arg.AreaID,
		arg.DoorID,
		arg.Schedule,
		arg.Members,
		arg.Status,
		arg.UpdatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionAccessUser = `-- name: UpsertProjectionAccessUser :exec
insert into mistypass_access_users (id, tenant_id, building_id, name, email, role, status, group_ids, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    building_id = excluded.building_id,
    name = excluded.name,
    email = excluded.email,
    role = excluded.role,
    status = excluded.status,
    group_ids = excluded.group_ids,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionAccessUserParams struct {
	ID         string
	TenantID   string
	BuildingID sql.NullString
	Name       string
	Email      string
	Role       string
	Status     string
	GroupIds   pqtype.NullRawMessage
	CreatedAt  time.Time
	Raw        json.RawMessage
}

func (q *Queries) UpsertProjectionAccessUser(ctx context.Context, arg UpsertProjectionAccessUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionAccessUser,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.GroupIds,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionAccessUserGroup = `-- name: UpsertProjectionAccessUserGroup :exec
insert into mistypass_access_user_groups (id, tenant_id, building_id, name, description, members, created_at, updated_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    building_id = excluded.building_id,
    name = excluded.name,
    description = excluded.description,
    members = excluded.members,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionAccessUserGroupParams struct {
	ID          string
	TenantID    string
	BuildingID  sql.NullString
	Name        string
	Description sql.NullString
	Members     pqtype.NullRawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Raw         json.RawMessage
}

func (q *Queries) UpsertProjectionAccessUserGroup(ctx context.Context, arg UpsertProjectionAccessUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionAccessUserGroup,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.Name,
		arg.Description,
		arg.Members,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionTemporaryAccess = `-- name: UpsertProjectionTemporaryAccess :exec
insert into mistypass_temporary_access (id, tenant_id, scope_type, building_id, area_id, door_id, delivery_method, grantee_name, grantee_email, grantee_phone, valid_until, authorized_by_email, authorized_by_role, authorized_at, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    scope_type = excluded.scope_type,
    building_id = excluded.building_id,
    area_id = excluded.area_id,
    door_id = excluded.door_id,
    delivery_method = excluded.delivery_method,
    grantee_name = excluded.grantee_name,
    grantee_email = excluded.grantee_email,
    grantee_phone = excluded.grantee_phone,
    valid_until = excluded.valid_until,
    authorized_by_email = excluded.authorized_by_email,
    authorized_by_role = excluded.authorized_by_role,
    authorized_at = excluded.authorized_at,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionTemporaryAccessParams struct {
	ID                string
	TenantID          string
	ScopeType         string
	BuildingID        sql.NullString
	AreaID            sql.NullString
	DoorID            sql.NullString
	DeliveryMethod    string
	GranteeName       string
	GranteeEmail      string
	GranteePhone      string
	ValidUntil        string
	AuthorizedByEmail sql.NullString
	AuthorizedByRole  sql.NullString
	AuthorizedAt      time.Time
	CreatedAt         time.Time
	Raw               json.RawMessage
}

func (q *Queries) UpsertProjectionTemporaryAccess(ctx context.Context, arg UpsertProjectionTemporaryAccessParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionTemporaryAccess,
		arg.ID,
		arg.TenantID,
		arg.ScopeType,
		arg.BuildingID,
		arg.AreaID,
		arg.DoorID,
		arg.DeliveryMethod,
		arg.GranteeName,
		arg.GranteeEmail,
		arg.GranteePhone,
		arg.ValidUntil,
		arg.AuthorizedByEmail,
		arg.AuthorizedByRole,
		arg.AuthorizedAt,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionVisitorPass = `-- name: UpsertProjectionVisitorPass :exec
insert into mistypass_visitor_passes (id, tenant_id, building_id, host, visitor, delivery_method, expires_at, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    building_id = excluded.building_id,
    host = excluded.host,
    visitor = excluded.visitor,
    delivery_method = excluded.delivery_method,
    expires_at = excluded.expires_at,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionVisitorPassParams struct {
	ID             string
	TenantID       string
	BuildingID     sql.NullString
	Host           string
	Visitor        string
	DeliveryMethod string
	ExpiresAt      string
	CreatedAt      time.Time
	Raw            json.RawMessage
}

func (q *Queries) UpsertProjectionVisitorPass(ctx context.Context, arg UpsertProjectionVisitorPassParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionVisitorPass,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.Host,
		arg.Visitor,
		arg.DeliveryMethod,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}
