// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projection_core.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const upsertProjectionAccessEvent = `-- name: UpsertProjectionAccessEvent :exec
insert into mistypass_access_events (id, tenant_id, building_id, area_id, event_type, actor, door_id, gateway_id, result, at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
on conflict (id, at) do update
set tenant_id = excluded.tenant_id,
    building_id = excluded.building_id,
    area_id = excluded.area_id,
    event_type = excluded.event_type,
    actor = excluded.actor,
    door_id = excluded.door_id,
    gateway_id = excluded.gateway_id,
    result = excluded.result,
    at = excluded.at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionAccessEventParams struct {
	ID         string
	TenantID   string
	BuildingID sql.NullString
	AreaID     sql.NullString
	EventType  sql.NullString
	Actor      sql.NullString
	DoorID     sql.NullString
	GatewayID  sql.NullString
	Result     sql.NullString
	At         time.Time
	Raw        json.RawMessage
}

func (q *Queries) UpsertProjectionAccessEvent(ctx context.Context, arg UpsertProjectionAccessEventParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionAccessEvent,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.AreaID,
		arg.EventType,
		arg.Actor,
		arg.DoorID,
		arg.GatewayID,
		arg.Result,
		arg.At,
		arg.Raw,
	)
	return err
}

const upsertProjectionAlarm = `-- name: UpsertProjectionAlarm :exec
insert into mistypass_alarms (id, tenant_id, building_id, area_id, door_id, alarm_type, severity, location, status, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    building_id = excluded.building_id,
    area_id = excluded.area_id,
    door_id = excluded.door_id,
    alarm_type = excluded.alarm_type,
    severity = excluded.severity,
    location = excluded.location,
    status = excluded.status,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionAlarmParams struct {
	ID         string
	TenantID   string
	BuildingID sql.NullString
	AreaID     sql.NullString
	DoorID     sql.NullString
	AlarmType  sql.NullString
	Severity   sql.NullString
	Location   sql.NullString
	Status     sql.NullString
	CreatedAt  time.Time
	Raw        json.RawMessage
}

func (q *Queries) UpsertProjectionAlarm(ctx context.Context, arg UpsertProjectionAlarmParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionAlarm,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.AreaID,
		arg.DoorID,
		arg.AlarmType,
		arg.Severity,
		arg.Location,
		arg.Status,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}

const upsertProjectionAuditLog = `-- name: UpsertProjectionAuditLog :exec
insert into mistypass_audit_logs (id, tenant_id, actor, role, action, target, source, at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
on conflict (id) do update
set tenant_id = excluded.tenant_id,
    actor = excluded.actor,
    role = excluded.role,
    action = excluded.action,
    target = excluded.target,
    source = excluded.source,
    at = excluded.at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionAuditLogParams struct {
	ID       string
	TenantID string
	Actor    sql.NullString
	Role     sql.NullString
	Action   sql.NullString
	Target   sql.NullString
	Source   sql.NullString
	At       time.Time
	Raw      json.RawMessage
}

func (q *Queries) UpsertProjectionAuditLog(ctx context.Context, arg UpsertProjectionAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionAuditLog,
		arg.ID,
		arg.TenantID,
		arg.Actor,
		arg.Role,
		arg.Action,
		arg.Target,
		arg.Source,
		arg.At,
		arg.Raw,
	)
	return err
}

const upsertProjectionDeviceEvent = `-- name: UpsertProjectionDeviceEvent :exec
insert into mistypass_device_events (id, tenant_id, building_id, event_type, gateway_id, detail, result, at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
on conflict (id, at) do update
set tenant_id = excluded.tenant_id,
    building_id = excluded.building_id,
    event_type = excluded.event_type,
    gateway_id = excluded.gateway_id,
    detail = excluded.detail,
    result = excluded.result,
    at = excluded.at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionDeviceEventParams struct {
	ID         string
	TenantID   string
	BuildingID sql.NullString
	EventType  sql.NullString
	GatewayID  sql.NullString
	Detail     sql.NullString
	Result     sql.NullString
	At         time.Time
	Raw        json.RawMessage
}

func (q *Queries) UpsertProjectionDeviceEvent(ctx context.Context, arg UpsertProjectionDeviceEventParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionDeviceEvent,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.EventType,
		arg.GatewayID,
		arg.Detail,
		arg.Result,
		arg.At,
		arg.Raw,
	)
	return err
}

const upsertProjectionTenant = `-- name: UpsertProjectionTenant :exec
insert into mistypass_tenants (id, name, tenant_type, hq_region, status, created_at, raw, synced_at)
values ($1, $2, $3, $4, $5, $6, $7, now())
on conflict (id) do update
set name = excluded.name,
    tenant_type = excluded.tenant_type,
    hq_region = excluded.hq_region,
    status = excluded.status,
    created_at = excluded.created_at,
    raw = excluded.raw,
    synced_at = now()
`

type UpsertProjectionTenantParams struct {
	ID         string
	Name       string
	TenantType string
	HqRegion   string
	Status     string
	CreatedAt  time.Time
	Raw        json.RawMessage
}

func (q *Queries) UpsertProjectionTenant(ctx context.Context, arg UpsertProjectionTenantParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionTenant,
		arg.ID,
		arg.Name,
		arg.TenantType,
		arg.HqRegion,
		arg.Status,
		arg.CreatedAt,
		arg.Raw,
	)
	return err
}
