// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: state_changes.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const getReplayCheckpointByKey = `-- name: GetReplayCheckpointByKey :one
select state_key, last_change_id, updated_at
from mistypass_change_replay_checkpoints
where state_key = $1
`

func (q *Queries) GetReplayCheckpointByKey(ctx context.Context, stateKey string) (MistypassChangeReplayCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getReplayCheckpointByKey, stateKey)
	var i MistypassChangeReplayCheckpoint
	err := row.Scan(&i.StateKey, &i.LastChangeID, &i.UpdatedAt)
	return i, err
}

const getStatePayload = `-- name: GetStatePayload :one
select payload
from mistypass
where state_key = $1
`

func (q *Queries) GetStatePayload(ctx context.Context, stateKey string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getStatePayload, stateKey)
	var payload json.RawMessage
	err := row.Scan(&payload)
	return payload, err
}

const getStatePayloadForUpdate = `-- name: GetStatePayloadForUpdate :one
select payload
from mistypass
where state_key = $1
for update
`

func (q *Queries) GetStatePayloadForUpdate(ctx context.Context, stateKey string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getStatePayloadForUpdate, stateKey)
	var payload json.RawMessage
	err := row.Scan(&payload)
	return payload, err
}

const insertStateChange = `-- name: InsertStateChange :one
insert into mistypass_change_log (state_key, change_type, payload_hash, payload, created_at)
values ($1, $2, $3, $4, now())
returning id
`

type InsertStateChangeParams struct {
	StateKey    string
	ChangeType  string
	PayloadHash string
	Payload     json.RawMessage
}

func (q *Queries) InsertStateChange(ctx context.Context, arg InsertStateChangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStateChange,
		arg.StateKey,
		arg.ChangeType,
		arg.PayloadHash,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listReplayCheckpointsAll = `-- name: ListReplayCheckpointsAll :many
select state_key, last_change_id, updated_at
from mistypass_change_replay_checkpoints
order by updated_at desc, state_key asc
limit $1
`

func (q *Queries) ListReplayCheckpointsAll(ctx context.Context, limit int32) ([]MistypassChangeReplayCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listReplayCheckpointsAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MistypassChangeReplayCheckpoint
	for rows.Next() {
		var i MistypassChangeReplayCheckpoint
		if err := rows.Scan(&i.StateKey, &i.LastChangeID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayCheckpointsByKey = `-- name: ListReplayCheckpointsByKey :many
select state_key, last_change_id, updated_at
from mistypass_change_replay_checkpoints
where state_key = $1
order by updated_at desc
limit $2
`

type ListReplayCheckpointsByKeyParams struct {
	StateKey string
	Limit    int32
}

func (q *Queries) ListReplayCheckpointsByKey(ctx context.Context, arg ListReplayCheckpointsByKeyParams) ([]MistypassChangeReplayCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listReplayCheckpointsByKey, arg.StateKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MistypassChangeReplayCheckpoint
	for rows.Next() {
		var i MistypassChangeReplayCheckpoint
		if err := rows.Scan(&i.StateKey, &i.LastChangeID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayPayloadsByKeyFromID = `-- name: ListReplayPayloadsByKeyFromID :many
select id, payload
from mistypass_change_log
where state_key = $1 and id > $2
order by id asc
limit $3
`

type ListReplayPayloadsByKeyFromIDParams struct {
	StateKey string
	ID       int64
	Limit    int32
}

type ListReplayPayloadsByKeyFromIDRow struct {
	ID      int64
	Payload json.RawMessage
}

func (q *Queries) ListReplayPayloadsByKeyFromID(ctx context.Context, arg ListReplayPayloadsByKeyFromIDParams) ([]ListReplayPayloadsByKeyFromIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listReplayPayloadsByKeyFromID, arg.StateKey, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReplayPayloadsByKeyFromIDRow
	for rows.Next() {
		var i ListReplayPayloadsByKeyFromIDRow
		if err := rows.Scan(&i.ID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStateChangesAll = `-- name: ListStateChangesAll :many
select id, state_key, change_type, payload_hash, payload, created_at
from mistypass_change_log
order by id desc
limit $1
`

func (q *Queries) ListStateChangesAll(ctx context.Context, limit int32) ([]MistypassChangeLog, error) {
	rows, err := q.db.QueryContext(ctx, listStateChangesAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MistypassChangeLog
	for rows.Next() {
		var i MistypassChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.StateKey,
			&i.ChangeType,
			&i.PayloadHash,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStateChangesByKey = `-- name: ListStateChangesByKey :many
select id, state_key, change_type, payload_hash, payload, created_at
from mistypass_change_log
where state_key = $1
order by id desc
limit $2
`

type ListStateChangesByKeyParams struct {
	StateKey string
	Limit    int32
}

func (q *Queries) ListStateChangesByKey(ctx context.Context, arg ListStateChangesByKeyParams) ([]MistypassChangeLog, error) {
	rows, err := q.db.QueryContext(ctx, listStateChangesByKey, arg.StateKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MistypassChangeLog
	for rows.Next() {
		var i MistypassChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.StateKey,
			&i.ChangeType,
			&i.PayloadHash,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReplayCheckpoint = `-- name: UpsertReplayCheckpoint :one
insert into mistypass_change_replay_checkpoints (state_key, last_change_id, updated_at)
values ($1, $2, now())
on conflict (state_key) do update
set last_change_id = greatest(mistypass_change_replay_checkpoints.last_change_id, excluded.last_change_id),
    updated_at = now()
returning state_key, last_change_id, updated_at
`

type UpsertReplayCheckpointParams struct {
	StateKey     string
	LastChangeID int64
}

func (q *Queries) UpsertReplayCheckpoint(ctx context.Context, arg UpsertReplayCheckpointParams) (MistypassChangeReplayCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, upsertReplayCheckpoint, arg.StateKey, arg.LastChangeID)
	var i MistypassChangeReplayCheckpoint
	err := row.Scan(&i.StateKey, &i.LastChangeID, &i.UpdatedAt)
	return i, err
}

const upsertStatePayload = `-- name: UpsertStatePayload :exec
insert into mistypass (state_key, payload, updated_at)
values ($1, $2, now())
on conflict (state_key) do update
set payload = excluded.payload,
    updated_at = now()
`

type UpsertStatePayloadParams struct {
	StateKey string
	Payload  json.RawMessage
}

func (q *Queries) UpsertStatePayload(ctx context.Context, arg UpsertStatePayloadParams) error {
	_, err := q.db.ExecContext(ctx, upsertStatePayload, arg.StateKey, arg.Payload)
	return err
}
