import { request, requestItems, withTenantQuery, encodePathSegment } from "./core"
import type { ListPageOptions } from "./core"

export type WalletPassTemplate = { id: string; tenant_id: string; provider: string; pass_type: "employee" | "visitor"; class_id: string; name: string; style_config?: Record<string, string>; status: "active" | "inactive"; created_at: string; updated_at: string }
export type WalletPassInstance = { id: string; tenant_id: string; provider: string; template_id: string; target_type: "user" | "visitor"; target_id: string; object_id: string; status: "issued" | "active" | "suspended" | "revoked"; save_link: string; expires_at?: string; issued_at: string; activated_at?: string; revoked_at?: string; created_by: string; updated_by: string; created_at: string; updated_at: string }
export type Card = { id: string; resource_type: "Card"; tenant_id: string; status: "activated" | "deactivated" | "unassigned" | "revoked"; token: string; uid?: string; card_number?: string; provider: string; credential_kind: "google_wallet" | "apple_wallet" | "physical_card" | "credential"; template_id: string; user_id?: string; assignee_type?: "User" | "Guest"; assignee_id?: string; activation_token?: string; save_link?: string; last_used_at?: string; issued_at: string; expires_at?: string; created_at: string; updated_at: string }
export type CardAssignment = { id: string; resource_type: "CardAssignment"; tenant_id: string; status: "activated" | "deactivated"; card_id: string; card: Card; assignee_type: "User" | "Guest"; assignee_id: string; user_id?: string; created_at: string; updated_at: string }
export type WalletPhysicalCardTask = { id: string; tenant_id: string; pass_id: string; template_id: string; target_type: "user" | "visitor"; target_id: string; task_type: "issue" | "reissue" | "loss_report"; status: "queued" | "printing" | "ready" | "issued" | "reported_lost" | "cancelled"; card_number?: string; inventory_id?: string; vendor_id?: string; vendor_name?: string; note?: string; pass_status: "issued" | "active" | "suspended" | "revoked"; completed_at?: string; created_by: string; updated_by: string; created_at: string; updated_at: string }
export type WalletPhysicalCardVendor = { id: string; tenant_id: string; name: string; provider: string; status: "active" | "inactive" | string; created_at: string; updated_at: string }
export type WalletPhysicalCardInventoryGovernanceStatus = "available" | "frozen" | "scrapped"
export type WalletPhysicalCardInventoryItem = { id: string; tenant_id: string; card_number: string; uid?: string; vendor_id?: string; vendor_name?: string; source?: string; reader_id?: string; status: "available" | "reserved" | "issued" | "lost" | "frozen" | "scrapped"; assigned_pass_id?: string; active_task_id?: string; scanned_at?: string; created_at: string; updated_at: string }
export type WalletPassDeliveryNotification = { id: string; tenant_id: string; pass_id: string; template_id: string; target_type: "user" | "visitor"; target_id: string; channels?: string[]; status: "sent" | "skipped" | "failed"; reason?: string; attempt?: number; retryable: boolean; provider?: string; provider_error?: string; channel_results?: Array<{ channel: string; status: "sent" | "skipped" | "failed"; reason?: string; provider?: string; provider_error?: string; retryable: boolean; receivers?: string[] }>; source_notification_id?: string; triggered_at: string }
export type WalletIssueJob = { id: string; tenant_id: string; provider: string; batch_id: string; template_id: string; target_type: "user" | "visitor"; target_id: string; expires_at?: string; pass_id?: string; status: string; retry_count: number; error_code?: string; error_message?: string; created_at: string; updated_at: string }
export type WalletJobSummary = { tenant_id: string; max_retry: number; total: number; pending: number; processing: number; success: number; failed: number; dlq: number; retryable_failed: number; non_retryable_failed: number; error_code_breakdown?: Record<string, number>; updated_at: string }
export type WalletJobMetricsWindow = { window_seconds: number; since: string; until: string; created: number; updated: number; pending: number; processing: number; success: number; failed: number; dlq: number; error_code_breakdown?: Record<string, number> }
export type WalletJobMetricsAlert = { type: string; error_code?: string; count: number; threshold: number }
export type WalletJobMetrics = { tenant_id: string; max_retry: number; dlq_alert_threshold: number; summary: WalletJobSummary; window: WalletJobMetricsWindow; alerts?: WalletJobMetricsAlert[]; updated_at: string }
export type WalletJobMetricsTrendBucket = { index: number; start: string; end: string; created: number; updated: number; pending: number; processing: number; success: number; failed: number; dlq: number; error_code_breakdown?: Record<string, number> }
export type WalletJobMetricsTrend = { tenant_id: string; max_retry: number; dlq_alert_threshold: number; window_seconds: number; bucket_seconds: number; bucket_count: number; since: string; until: string; summary: WalletJobSummary; alerts?: WalletJobMetricsAlert[]; buckets: WalletJobMetricsTrendBucket[]; updated_at: string }
export type WalletDLQCleanupArchive = { id: string; tenant_id: string; limit: number; error_code?: string; older_than_seconds: number; actor: string; removed: number; remaining_dlq: number; processed_jobs?: string[]; at: string }
export type WalletJobAlertSubscription = { tenant_id: string; enabled: boolean; dlq_alert_threshold: number; window_seconds: number; cooldown_seconds: number; channels: { email: boolean; whatsapp: boolean }; receiver_groups?: string[]; updated_at: string }
export type WalletJobAlertNotification = { id: string; tenant_id: string; type: string; error_code?: string; count: number; threshold: number; channels?: string[]; receiver_groups?: string[]; status: "sent" | "skipped" | "failed"; reason?: string; idempotency_key?: string; attempt?: number; retryable: boolean; provider?: string; provider_error?: string; channel_results?: Array<{ channel: string; status: "sent" | "skipped" | "failed"; reason?: string; provider?: string; provider_error?: string; retryable: boolean; receivers?: string[] }>; source_notification_id?: string; triggered_at: string }
export type WalletJobAlertDispatchResult = { tenant_id: string; window_seconds: number; max_retry: number; dlq_alert_threshold: number; total_alerts: number; dispatched: number; skipped: number; failed: number; items?: WalletJobAlertNotification[]; updated_at: string }

// --- Wallet Pass card adapter helpers ---

function walletPassStatusFromCard(status: Card["status"]): WalletPassInstance["status"] {
  switch (status) {
    case "activated": return "active"
    case "deactivated": return "suspended"
    case "revoked": return "revoked"
    case "unassigned":
    default: return "issued"
  }
}

function walletPassFromCard(card: Card): WalletPassInstance {
  const targetType: WalletPassInstance["target_type"] = card.assignee_type === "Guest" ? "visitor" : "user"
  return {
    id: card.id, tenant_id: card.tenant_id, provider: card.provider, template_id: card.template_id, target_type: targetType,
    target_id: card.assignee_id || card.user_id || "", object_id: card.token || card.uid || card.card_number || card.id,
    status: walletPassStatusFromCard(card.status), save_link: card.save_link ?? "", expires_at: card.expires_at,
    issued_at: card.issued_at, created_by: "", updated_by: "", created_at: card.created_at, updated_at: card.updated_at,
  }
}

// --- Templates ---
export async function listWalletTemplates(token: string | undefined, tenantID?: string): Promise<WalletPassTemplate[]> { return requestItems<WalletPassTemplate>(withTenantQuery("/api/v1/wallet/templates", tenantID), token) }
export async function createWalletTemplate(token: string | undefined, payload: { tenant_id: string; pass_type: "employee" | "visitor"; class_id?: string; name: string; style_config?: Record<string, string>; status?: "active" | "inactive"; actor?: string }): Promise<WalletPassTemplate> { return request<WalletPassTemplate>("/api/v1/wallet/templates", { method: "POST", body: JSON.stringify(payload) }, token) }
export async function updateWalletTemplateStatus(token: string | undefined, templateID: string, payload: { tenant_id: string; status: "active" | "inactive"; actor?: string }): Promise<WalletPassTemplate> { return request<WalletPassTemplate>(withTenantQuery(`/api/v1/wallet/templates/${encodePathSegment(templateID)}/status`, payload.tenant_id), { method: "PATCH", body: JSON.stringify({ status: payload.status, actor: payload.actor }) }, token) }

// --- Passes ---
export async function issueWalletPass(token: string | undefined, payload: { tenant_id: string; template_id: string; target_type: "user" | "visitor"; target_id: string; expires_at?: string; actor?: string }): Promise<WalletPassInstance> { return request<WalletPassInstance>("/api/v1/wallet/passes/issue", { method: "POST", body: JSON.stringify(payload) }, token) }
export async function issueWalletPassBatch(token: string | undefined, payload: { tenant_id: string; template_id: string; target_type: "user" | "visitor"; target_ids: string[]; expires_at?: string; actor?: string; execution_mode?: "inline" | "queued" }): Promise<{ items: WalletIssueJob[]; execution_mode: "inline" | "queued" }> { return request("/api/v1/wallet/passes/issue-batch", { method: "POST", body: JSON.stringify(payload) }, token) }
export async function listWalletJobs(token: string | undefined, tenantID?: string): Promise<WalletIssueJob[]> { return requestItems<WalletIssueJob>(withTenantQuery("/api/v1/wallet/jobs", tenantID), token) }

export async function listWalletPasses(token: string | undefined, tenantID?: string, options?: ListPageOptions): Promise<WalletPassInstance[]> {
  const cards = await listCards(token, tenantID ? { tenant_id: tenantID } : undefined)
  const items = cards.map(walletPassFromCard)
  const page = typeof options?.page === "number" && Number.isFinite(options.page) && options.page > 0 ? Math.floor(options.page) : 1
  const limit = typeof options?.limit === "number" && Number.isFinite(options.limit) && options.limit > 0 ? Math.floor(options.limit) : items.length
  return items.slice((page - 1) * limit, page * limit)
}

export async function getWalletPass(token: string | undefined, passID: string, tenantID?: string): Promise<WalletPassInstance> { return request<WalletPassInstance>(withTenantQuery(`/api/v1/wallet/passes/${encodePathSegment(passID)}`, tenantID), { method: "GET" }, token) }
export async function getWalletPassSaveLink(token: string | undefined, passID: string, tenantID?: string): Promise<string> { const payload = await request<{ save_link: string }>(withTenantQuery(`/api/v1/wallet/passes/${encodePathSegment(passID)}/save-link`, tenantID), { method: "GET" }, token); return payload.save_link }

async function updateWalletPassStatus(token: string | undefined, passID: string, action: "suspend" | "activate" | "revoke", payload: { tenant_id: string; actor?: string }): Promise<WalletPassInstance> { return request<WalletPassInstance>(withTenantQuery(`/api/v1/wallet/passes/${encodePathSegment(passID)}/${action}`, payload.tenant_id), { method: "PATCH", body: JSON.stringify({ actor: payload.actor }) }, token) }
export async function suspendWalletPass(token: string | undefined, passID: string, payload: { tenant_id: string; actor?: string }): Promise<WalletPassInstance> { return updateWalletPassStatus(token, passID, "suspend", payload) }
export async function activateWalletPass(token: string | undefined, passID: string, payload: { tenant_id: string; actor?: string }): Promise<WalletPassInstance> { return updateWalletPassStatus(token, passID, "activate", payload) }
export async function revokeWalletPass(token: string | undefined, passID: string, payload: { tenant_id: string; actor?: string }): Promise<WalletPassInstance> { return updateWalletPassStatus(token, passID, "revoke", payload) }

// --- Physical Card Tasks / Vendors / Inventory ---
export async function listWalletPhysicalCardTasks(token: string | undefined, tenantID?: string): Promise<WalletPhysicalCardTask[]> { return requestItems<WalletPhysicalCardTask>(withTenantQuery("/api/v1/wallet/physical-card-tasks", tenantID), token) }
export async function listWalletPhysicalCardVendors(token: string | undefined, tenantID?: string): Promise<WalletPhysicalCardVendor[]> { return requestItems<WalletPhysicalCardVendor>(withTenantQuery("/api/v1/wallet/physical-card-vendors", tenantID), token) }
export async function listWalletPhysicalCardInventory(token: string | undefined, options?: { tenant_id?: string; status?: WalletPhysicalCardInventoryItem["status"] }): Promise<WalletPhysicalCardInventoryItem[]> { const query = new URLSearchParams(); if (options?.tenant_id?.trim()) query.set("tenant_id", options.tenant_id.trim()); if (options?.status?.trim()) query.set("status", options.status.trim()); const suffix = query.toString(); return requestItems<WalletPhysicalCardInventoryItem>(suffix ? `/api/v1/wallet/physical-card-inventory?${suffix}` : "/api/v1/wallet/physical-card-inventory", token) }
export async function createWalletPhysicalCardInventoryItem(token: string | undefined, payload: { tenant_id: string; card_number: string; uid?: string; vendor_id?: string; status?: WalletPhysicalCardInventoryItem["status"]; actor?: string }): Promise<WalletPhysicalCardInventoryItem> { return request<WalletPhysicalCardInventoryItem>("/api/v1/wallet/physical-card-inventory", { method: "POST", body: JSON.stringify(payload) }, token) }
export async function scanWalletPhysicalCardInventoryItem(token: string | undefined, payload: { tenant_id: string; uid: string; card_number?: string; reader_id?: string; vendor_id?: string; actor?: string }): Promise<WalletPhysicalCardInventoryItem> { return request<WalletPhysicalCardInventoryItem>("/api/v1/wallet/physical-card-inventory/scan", { method: "POST", body: JSON.stringify(payload) }, token) }
export async function importWalletPhysicalCardInventory(token: string | undefined, payload: { tenant_id: string; items: Array<{ card_number: string; uid?: string; vendor_id?: string; status?: WalletPhysicalCardInventoryItem["status"] }>; actor?: string }): Promise<WalletPhysicalCardInventoryItem[]> { const response = await request<{ items: WalletPhysicalCardInventoryItem[] }>("/api/v1/wallet/physical-card-inventory/import", { method: "POST", body: JSON.stringify(payload) }, token); return response.items ?? [] }
export async function importWalletPhysicalCardInventoryCSV(token: string | undefined, payload: { tenant_id: string; csv_content: string; actor?: string }): Promise<WalletPhysicalCardInventoryItem[]> { const response = await request<{ items: WalletPhysicalCardInventoryItem[] }>("/api/v1/wallet/physical-card-inventory/import-csv", { method: "POST", body: JSON.stringify(payload) }, token); return response.items ?? [] }
export async function updateWalletPhysicalCardInventoryStatus(token: string | undefined, inventoryID: string, payload: { tenant_id: string; status: WalletPhysicalCardInventoryGovernanceStatus; reason?: string; actor?: string }): Promise<WalletPhysicalCardInventoryItem> { return request<WalletPhysicalCardInventoryItem>(`/api/v1/wallet/physical-card-inventory/${encodePathSegment(inventoryID)}/status`, { method: "PATCH", body: JSON.stringify(payload) }, token) }
export async function batchUpdateWalletPhysicalCardInventoryStatus(token: string | undefined, payload: { tenant_id: string; inventory_ids: string[]; status: WalletPhysicalCardInventoryGovernanceStatus; reason?: string; actor?: string }): Promise<WalletPhysicalCardInventoryItem[]> { const response = await request<{ items: WalletPhysicalCardInventoryItem[] }>("/api/v1/wallet/physical-card-inventory/batch-status", { method: "PATCH", body: JSON.stringify(payload) }, token); return response.items ?? [] }

// --- Deliveries ---
export async function listWalletPassDeliveries(token: string | undefined, payload: { tenant_id: string; pass_id?: string }): Promise<WalletPassDeliveryNotification[]> { const params = new URLSearchParams(); if (payload.tenant_id.trim()) params.set("tenant_id", payload.tenant_id.trim()); if (payload.pass_id?.trim()) params.set("pass_id", payload.pass_id.trim()); const suffix = params.toString(); return requestItems<WalletPassDeliveryNotification>(suffix ? `/api/v1/wallet/deliveries?${suffix}` : "/api/v1/wallet/deliveries", token) }
export async function dispatchWalletPassDelivery(token: string | undefined, payload: { tenant_id: string; pass_id: string; channels: string[]; email_recipients?: string[]; whatsapp_recipients?: string[]; actor?: string }): Promise<WalletPassDeliveryNotification> { return request<WalletPassDeliveryNotification>("/api/v1/wallet/deliveries/dispatch", { method: "POST", body: JSON.stringify(payload) }, token) }
export async function retryWalletPassDelivery(token: string | undefined, payload: { tenant_id: string; notification_id: string; actor?: string }): Promise<WalletPassDeliveryNotification> { return request<WalletPassDeliveryNotification>(`/api/v1/wallet/deliveries/${encodeURIComponent(payload.notification_id)}/retry`, { method: "POST", body: JSON.stringify({ tenant_id: payload.tenant_id, actor: payload.actor }) }, token) }

// --- Physical Card Tasks ---
export async function createWalletPhysicalCardTask(token: string | undefined, payload: { tenant_id: string; pass_id: string; task_type: "issue" | "reissue" | "loss_report"; card_number?: string; inventory_id?: string; vendor_id?: string; note?: string; actor?: string }): Promise<WalletPhysicalCardTask> { return request<WalletPhysicalCardTask>("/api/v1/wallet/physical-card-tasks", { method: "POST", body: JSON.stringify(payload) }, token) }
export async function updateWalletPhysicalCardTaskStatus(token: string | undefined, taskID: string, payload: { tenant_id: string; status: string; card_number?: string; note?: string; actor?: string }): Promise<WalletPhysicalCardTask> { return request<WalletPhysicalCardTask>(withTenantQuery(`/api/v1/wallet/physical-card-tasks/${encodePathSegment(taskID)}/status`, payload.tenant_id), { method: "PATCH", body: JSON.stringify({ status: payload.status, card_number: payload.card_number, note: payload.note, actor: payload.actor }) }, token) }

// --- Cards ---
export async function listCards(token: string | undefined, options?: { tenant_id?: string; ids?: string[]; status?: Card["status"]; provider?: string; credential_kind?: Card["credential_kind"]; user_id?: string; token?: string; uid?: string; card_number?: string; card_id?: string }): Promise<Card[]> { const query = new URLSearchParams(); if (options?.tenant_id?.trim()) query.set("tenant_id", options.tenant_id.trim()); if (options?.ids && options.ids.length > 0) query.set("ids", options.ids.join(",")); if (options?.status?.trim()) query.set("status", options.status.trim()); if (options?.provider?.trim()) query.set("provider", options.provider.trim()); if (options?.credential_kind?.trim()) query.set("credential_kind", options.credential_kind.trim()); if (options?.user_id?.trim()) query.set("user_id", options.user_id.trim()); if (options?.token?.trim()) query.set("token", options.token.trim()); if (options?.uid?.trim()) query.set("uid", options.uid.trim()); if (options?.card_number?.trim()) query.set("card_number", options.card_number.trim()); if (options?.card_id?.trim()) query.set("card_id", options.card_id.trim()); const suffix = query.toString(); return requestItems<Card>(suffix ? `/api/v1/cards?${suffix}` : "/api/v1/cards", token) }
export async function getCard(token: string | undefined, cardID: string, tenantID?: string): Promise<Card> { const query = new URLSearchParams(); if (tenantID?.trim()) query.set("tenant_id", tenantID.trim()); const suffix = query.toString(); return request<Card>(suffix ? `/api/v1/cards/${encodePathSegment(cardID)}?${suffix}` : `/api/v1/cards/${encodePathSegment(cardID)}`, { method: "GET" }, token) }
export async function listCardAssignments(token: string | undefined, options?: { tenant_id?: string; ids?: string[]; status?: CardAssignment["status"]; card_id?: string; assignee_type?: CardAssignment["assignee_type"]; assignee_id?: string; user_id?: string }): Promise<CardAssignment[]> { const query = new URLSearchParams(); if (options?.tenant_id?.trim()) query.set("tenant_id", options.tenant_id.trim()); if (options?.ids && options.ids.length > 0) query.set("ids", options.ids.join(",")); if (options?.status?.trim()) query.set("status", options.status.trim()); if (options?.card_id?.trim()) query.set("card_id", options.card_id.trim()); if (options?.assignee_type?.trim()) query.set("assignee_type", options.assignee_type.trim()); if (options?.assignee_id?.trim()) query.set("assignee_id", options.assignee_id.trim()); if (options?.user_id?.trim()) query.set("user_id", options.user_id.trim()); const suffix = query.toString(); return requestItems<CardAssignment>(suffix ? `/api/v1/card_assignments?${suffix}` : "/api/v1/card_assignments", token) }
export async function getCardAssignment(token: string | undefined, assignmentID: string, tenantID?: string): Promise<CardAssignment> { const query = new URLSearchParams(); if (tenantID?.trim()) query.set("tenant_id", tenantID.trim()); const suffix = query.toString(); return request<CardAssignment>(suffix ? `/api/v1/card_assignments/${encodePathSegment(assignmentID)}?${suffix}` : `/api/v1/card_assignments/${encodePathSegment(assignmentID)}`, { method: "GET" }, token) }
export async function createCard(token: string | undefined, payload: { tenant_id: string; template_id?: string; token?: string; uid?: string; card_number?: string; type?: string; assignee_type?: "User" | "Guest"; assignee_id?: string; user_id?: string; guest_id?: string; email?: string; expires_at?: string }): Promise<Card> { return request<Card>("/api/v1/cards", { method: "POST", body: JSON.stringify({ card: payload }) }, token) }
export async function createCardAssignment(token: string | undefined, payload: { tenant_id: string; card_id: string; assignee_type: "User" | "Guest"; assignee_id?: string; user_id?: string; guest_id?: string; email?: string }): Promise<CardAssignment> { return request<CardAssignment>("/api/v1/card_assignments", { method: "POST", body: JSON.stringify({ card_assignment: payload }) }, token) }
export async function assignCard(token: string | undefined, cardID: string, payload: { tenant_id: string; assignee_type?: "User" | "Guest"; assignee_id?: string; user_id?: string; guest_id?: string; email?: string }): Promise<Card> { return request<Card>(`/api/v1/cards/${encodePathSegment(cardID)}/assign`, { method: "POST", body: JSON.stringify({ card: payload }) }, token) }
export async function deassignCard(token: string | undefined, cardID: string, tenantID?: string): Promise<Card> { const query = new URLSearchParams(); if (tenantID?.trim()) query.set("tenant_id", tenantID.trim()); const suffix = query.toString(); return request<Card>(suffix ? `/api/v1/cards/${encodePathSegment(cardID)}/deassign?${suffix}` : `/api/v1/cards/${encodePathSegment(cardID)}/deassign`, { method: "POST" }, token) }
export async function activateCard(token: string | undefined, cardID: string, tenantID?: string): Promise<Card> { const query = new URLSearchParams(); if (tenantID?.trim()) query.set("tenant_id", tenantID.trim()); const suffix = query.toString(); return request<Card>(suffix ? `/api/v1/cards/${encodePathSegment(cardID)}/activate?${suffix}` : `/api/v1/cards/${encodePathSegment(cardID)}/activate`, { method: "POST" }, token) }
export async function deactivateCard(token: string | undefined, cardID: string, tenantID?: string): Promise<Card> { const query = new URLSearchParams(); if (tenantID?.trim()) query.set("tenant_id", tenantID.trim()); const suffix = query.toString(); return request<Card>(suffix ? `/api/v1/cards/${encodePathSegment(cardID)}/deactivate?${suffix}` : `/api/v1/cards/${encodePathSegment(cardID)}/deactivate`, { method: "POST" }, token) }
export async function revokeCard(token: string | undefined, cardID: string, tenantID?: string): Promise<Card> { const query = new URLSearchParams(); if (tenantID?.trim()) query.set("tenant_id", tenantID.trim()); const suffix = query.toString(); return request<Card>(suffix ? `/api/v1/cards/${encodePathSegment(cardID)}/revoke?${suffix}` : `/api/v1/cards/${encodePathSegment(cardID)}/revoke`, { method: "POST" }, token) }

// --- Job Metrics ---
function buildWalletJobMetricsPath(options: { tenant_id?: string; window_seconds?: number; max_retry?: number; dlq_alert_threshold?: number }): string { const query = new URLSearchParams(); if (options.tenant_id?.trim()) query.set("tenant_id", options.tenant_id.trim()); if (typeof options.window_seconds === "number" && options.window_seconds > 0) query.set("window_seconds", String(options.window_seconds)); if (typeof options.max_retry === "number" && options.max_retry >= 0) query.set("max_retry", String(options.max_retry)); if (typeof options.dlq_alert_threshold === "number" && options.dlq_alert_threshold > 0) query.set("dlq_alert_threshold", String(options.dlq_alert_threshold)); const suffix = query.toString(); return suffix ? `/api/v1/wallet/jobs/metrics?${suffix}` : "/api/v1/wallet/jobs/metrics" }
function buildWalletDLQCleanupArchivesPath(options: { tenant_id?: string; limit?: number }): string { const query = new URLSearchParams(); if (options.tenant_id?.trim()) query.set("tenant_id", options.tenant_id.trim()); if (typeof options.limit === "number" && options.limit > 0) query.set("limit", String(options.limit)); const suffix = query.toString(); return suffix ? `/api/v1/wallet/jobs/dlq/cleanup/archives?${suffix}` : "/api/v1/wallet/jobs/dlq/cleanup/archives" }
function buildWalletJobMetricsTrendPath(options: { tenant_id?: string; window_seconds?: number; bucket_count?: number; max_retry?: number; dlq_alert_threshold?: number }): string { const query = new URLSearchParams(); if (options.tenant_id?.trim()) query.set("tenant_id", options.tenant_id.trim()); if (typeof options.window_seconds === "number" && options.window_seconds > 0) query.set("window_seconds", String(options.window_seconds)); if (typeof options.bucket_count === "number" && options.bucket_count > 0) query.set("bucket_count", String(options.bucket_count)); if (typeof options.max_retry === "number" && options.max_retry >= 0) query.set("max_retry", String(options.max_retry)); if (typeof options.dlq_alert_threshold === "number" && options.dlq_alert_threshold > 0) query.set("dlq_alert_threshold", String(options.dlq_alert_threshold)); const suffix = query.toString(); return suffix ? `/api/v1/wallet/jobs/metrics/trend?${suffix}` : "/api/v1/wallet/jobs/metrics/trend" }
function buildWalletJobAlertSubscriptionPath(options: { tenant_id?: string }): string { const query = new URLSearchParams(); if (options.tenant_id?.trim()) query.set("tenant_id", options.tenant_id.trim()); const suffix = query.toString(); return suffix ? `/api/v1/wallet/jobs/alert-subscription?${suffix}` : "/api/v1/wallet/jobs/alert-subscription" }
function buildWalletJobAlertNotificationsPath(options: { tenant_id?: string; limit?: number }): string { const query = new URLSearchParams(); if (options.tenant_id?.trim()) query.set("tenant_id", options.tenant_id.trim()); if (typeof options.limit === "number" && options.limit > 0) query.set("limit", String(options.limit)); const suffix = query.toString(); return suffix ? `/api/v1/wallet/jobs/alert-notifications?${suffix}` : "/api/v1/wallet/jobs/alert-notifications" }

export async function getWalletJobMetrics(token: string | undefined, options: { tenant_id?: string; window_seconds?: number; max_retry?: number; dlq_alert_threshold?: number }): Promise<WalletJobMetrics> { return request<WalletJobMetrics>(buildWalletJobMetricsPath(options), { method: "GET" }, token) }
export async function listWalletDLQCleanupArchives(token: string | undefined, options: { tenant_id?: string; limit?: number }): Promise<WalletDLQCleanupArchive[]> { const payload = await request<{ items: WalletDLQCleanupArchive[] }>(buildWalletDLQCleanupArchivesPath(options), { method: "GET" }, token); return payload.items }
export async function getWalletJobMetricsTrend(token: string | undefined, options: { tenant_id?: string; window_seconds?: number; bucket_count?: number; max_retry?: number; dlq_alert_threshold?: number }): Promise<WalletJobMetricsTrend> { return request<WalletJobMetricsTrend>(buildWalletJobMetricsTrendPath(options), { method: "GET" }, token) }
export async function getWalletJobAlertSubscription(token: string | undefined, options: { tenant_id?: string }): Promise<WalletJobAlertSubscription> { return request<WalletJobAlertSubscription>(buildWalletJobAlertSubscriptionPath(options), { method: "GET" }, token) }
export async function upsertWalletJobAlertSubscription(token: string | undefined, payload: { tenant_id: string; enabled?: boolean; dlq_alert_threshold?: number; window_seconds?: number; cooldown_seconds?: number; channels?: { email?: boolean; whatsapp?: boolean }; receiver_groups?: string[]; actor?: string }): Promise<WalletJobAlertSubscription> { return request<WalletJobAlertSubscription>("/api/v1/wallet/jobs/alert-subscription", { method: "PUT", body: JSON.stringify(payload) }, token) }
export async function listWalletJobAlertNotifications(token: string | undefined, options: { tenant_id?: string; limit?: number }): Promise<WalletJobAlertNotification[]> { const payload = await request<{ items: WalletJobAlertNotification[] }>(buildWalletJobAlertNotificationsPath(options), { method: "GET" }, token); return payload.items }
export async function dispatchWalletJobAlerts(token: string | undefined, payload: { tenant_id: string; window_seconds?: number; max_retry?: number; dlq_alert_threshold?: number; actor?: string }): Promise<WalletJobAlertDispatchResult> { return request<WalletJobAlertDispatchResult>("/api/v1/wallet/jobs/alerts/dispatch", { method: "POST", body: JSON.stringify(payload) }, token) }
export async function retryWalletJobAlertNotification(token: string | undefined, payload: { tenant_id: string; notification_id: string; actor?: string }): Promise<WalletJobAlertNotification> { const notificationID = payload.notification_id.trim(); return request<WalletJobAlertNotification>(`/api/v1/wallet/jobs/alert-notifications/${encodeURIComponent(notificationID)}/retry`, { method: "POST", body: JSON.stringify({ tenant_id: payload.tenant_id, actor: payload.actor }) }, token) }
